from database.db import *


def post_text_parasha(
    nroParasha,
    nameParasha,
    signParasha,
    section1,
    aliya1,
    verso1,
    titleReflection1,
    reflection1,
    section2,
    aliya2,
    verso2,
    titleReflection2,
    reflection2,
    section3,
    aliya3,
    verso3,
    titleReflection3,
    reflection3,
    section4,
    aliya4,
    verso4,
    titleReflection4,
    reflection4,
    section5,
    aliya5,
    verso5,
    titleReflection5,
    reflection5,
    section6,
    aliya6,
    verso6,
    titleReflection6,
    reflection6,
    section7,
    aliya7,
    verso7,
    titleReflection7,
    reflection7,
    sectionHaftara,
    haftara,
):
    query = """INSERT INTO parasha (
    nroParasha,
    nameParasha,
    signParasha,
    section1,
    aliya1,
    verso1,
    titleReflection1,
    reflection1,
    section2,
    aliya2,
    verso2,
    titleReflection2,
    reflection2,
    section3,
    aliya3,
    verso3,
    titleReflection3,
    reflection3,
    section4,
    aliya4,
    verso4,
    titleReflection4,
    reflection4,
    section5,
    aliya5,
    verso5,
    titleReflection5,
    reflection5,
    section6,
    aliya6,
    verso6,
    titleReflection6,
    reflection6,
    section7,
    aliya7,
    verso7,
    titleReflection7,
    reflection7,
    sectionHaftara,
    haftara
) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"""

    params = (
        nroParasha,
        nameParasha,
        signParasha,
        section1,
        aliya1,
        verso1,
        titleReflection1,
        reflection1,
        section2,
        aliya2,
        verso2,
        titleReflection2,
        reflection2,
        section3,
        aliya3,
        verso3,
        titleReflection3,
        reflection3,
        section4,
        aliya4,
        verso4,
        titleReflection4,
        reflection4,
        section5,
        aliya5,
        verso5,
        titleReflection5,
        reflection5,
        section6,
        aliya6,
        verso6,
        titleReflection6,
        reflection6,
        section7,
        aliya7,
        verso7,
        titleReflection7,
        reflection7,
        sectionHaftara,
        haftara,
    )
    try:
        connection_DB = connection.cursor()
        connection_DB.execute(query, params)
        connection.commit()
        connection_DB.close()
    except sqlite3.Error as e:
        print("ERROR =>")
        print(f"COMMIT FAIL: {e}")
    else:
        print("SUCCES")

